name: BaseSkripsi API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2.0.0
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew bootJar
    - name: Copy To Server
      uses: nogsantos/scp-deploy@master
      with:
       src: build/libs/*.jar
       host: ${{ secrets.SSH_HOST }}
       remote: /home/${{ secrets.SSH_USER }}/project/basesripsiapi/build/libs
       port: 22
       user: ${{ secrets.SSH_USER }}
       key: ${{ secrets.SSH_KEY }}
